import axios from "axios"
import { getHeaders } from "../auth/authService"
// const B = "http://localhost:8000"
const BASE = import.meta.env.VITE_API_URL
export const login = (d) => axios.post(`${B}/login`, d)
export const changePassword = (d) => axios.post(`${B}/changePassword`, d)
export const getProfile = () => axios.get(`${B}/user/profile`, { headers: getHeaders() })
export const updateProfile = (d) => axios.post(`${B}/user/updateProfile`, d, { headers: getHeaders() })
export const getDashboardStats = () => axios.get(`${B}/admin/dashboardStats`, { headers: getHeaders() })
export const getAdminUsers = () => axios.get(`${B}/admin/users`, { headers: getHeaders() })
export const updateUserStatus = (d) => axios.post(`${B}/admin/updateUserStatus`, d, { headers: getHeaders() })
export const getAdminCities = () => axios.get(`${B}/admin/cities`, { headers: getHeaders() })
export const addCity = (d) => axios.post(`${B}/admin/addCity`, d, { headers: getHeaders() })
export const updateCity = (d) => axios.post(`${B}/admin/updateCity`, d, { headers: getHeaders() })
export const deleteCity = (id) => axios.get(`${B}/admin/deleteCity/${id}`, { headers: getHeaders() })
export const getAdminOccasions = () => axios.get(`${B}/admin/occasions`, { headers: getHeaders() })
export const addOccasion = (d) => axios.post(`${B}/admin/addOccasion`, d, { headers: getHeaders() })
export const updateOccasion = (d) => axios.post(`${B}/admin/updateOccasion`, d, { headers: getHeaders() })
export const deleteOccasion = (id) => axios.get(`${B}/admin/deleteOccasion/${id}`, { headers: getHeaders() })
export const getAdminVenueTypes = () => axios.get(`${B}/admin/venueTypes`, { headers: getHeaders() })
export const addVenueType = (d) => axios.post(`${B}/admin/addVenueType`, d, { headers: getHeaders() })
export const updateVenueType = (d) => axios.post(`${B}/admin/updateVenueType`, d, { headers: getHeaders() })
export const deleteVenueType = (id) => axios.get(`${B}/admin/deleteVenueType/${id}`, { headers: getHeaders() })
export const getAdminVenues = () => axios.get(`${B}/admin/venues`, { headers: getHeaders() })
export const addVenue = (d) => axios.post(`${B}/admin/addVenue`, d, { headers: getHeaders() })
export const updateVenue = (d) => axios.post(`${B}/admin/updateVenue`, d, { headers: getHeaders() })
export const deleteVenue = (id) => axios.get(`${B}/admin/deleteVenue/${id}`, { headers: getHeaders() })
export const getAdminBookings = () => axios.get(`${B}/admin/bookings`, { headers: getHeaders() })
export const updateBooking = (d) => axios.post(`${B}/admin/updateBooking`, d, { headers: getHeaders() })
export const getAdminPayments = () => axios.get(`${B}/admin/payments`, { headers: getHeaders() })
export const getAdminFeedbacks = () => axios.get(`${B}/admin/feedbacks`, { headers: getHeaders() })
